Make reponse for different content types
ems-project/EMSClientHelperBundle pull request #190
Opened 2020-12-28 14:02 UTC by laurensmertens

|Q              |A  |
|---------------|---|
|Bug fix?       |No|
|New feature?   |Yes|	
|BC breaks?     |No|	
|Deprecations?  |No|	
|Fixed tickets  |No|	

Created a makeResponse function to allow any header and any content specified in the template.

2020-12-29 09:21 UTC, Davidmattei requested changes

2020-12-29 09:24 UTC, laurensmertens commented on Controller/RouterController.php
> +        $response->setContent($data['content']);
@Davidmattei OK fixed

2020-12-29 09:56 UTC, Davidmattei submitted a review, later dismissed

2020-12-29 10:22 UTC, theus77 commented on Controller/RouterController.php
> +        $data = \json_decode($json, true);
The outcome of the json_encode must be tested (=== false?) and an error thrown.

2020-12-29 10:22 UTC, theus77 commented on Controller/RouterController.php
> +        $response->setContent($data['content']);
What if content is missing?

2020-12-29 10:22 UTC, theus77 commented on Controller/RouterController.php
> +        foreach ($data['headers'] as $key => $value) {
What if headers is missing?

2020-12-30 11:16 UTC, theus77 commented on Controller/RouterController.php
> +            throw new \RuntimeException('Failed to decode JSON');
Th error message should explain that a json is expected with at least a content field string

2020-12-30 11:16 UTC, theus77 commented on Controller/RouterController.php
> +        $response->setContent($data['content'] ?? null);
If content is missing you should raise an error with a message explaining that a json with a mandatory content field is required

2020-12-30 11:41 UTC, theus77 commented on Controller/RouterController.php
> +        if (!array_key_exists('content', $data)) {
```suggestion
        if (!\is_string($data['content'] ?? null)) {
```

2020-12-30 11:41 UTC, theus77 commented on Controller/RouterController.php
> +        $headers = $data['headers'] ?? ['Content-Type' => 'text/plain'];
```suggestion
        $headers = $data['headers'] ?? ['Content-Type' => 'text/plain'];
        
        
        if  (!\is_array($headers)) {
                throw new \RuntimeException('Unexpected non-array headers parameter');
        }
```

2020-12-30 12:05 UTC, theus77 approved these changes

2020-12-30 12:07 UTC, merged