Feat/core 2
ems-project/EMSClientHelperBundle pull request #192
Opened 2020-12-29 08:27 UTC by theus77

|Q              |A  |
|---------------|---|
|Bug fix?       |N|
|New feature?   |Y|	
|BC breaks?     |N|	
|Deprecations?  |N|	
|Fixed tickets  |N|	

Introduce an ignore environment not found exception

2020-12-29 09:03 UTC, Davidmattei requested changes
The EnvironmentNotFoundException is only throwed in the ClientRequest when calling getIndex, we should remove that throw and place it inside the EnvironmentHelper::getEnvironment()

Then you only need too inject the ignoreNotFoundEnvironment variable into the EnvironmentHelper and it works for the full code

2020-12-30 08:14 UTC, theus77 commented on Helper/Routing/Router.php
> +        }
Refactored

2020-12-30 09:18 UTC, Davidmattei commented on Helper/Routing/Router.php
> +        }
Very nice!

2020-12-30 12:10 UTC, Davidmattei approved these changes

2020-12-30 12:15 UTC, merged